<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Fri, 16 Sep 2016 09:17:34 +0930
 */

$conf['title'] = 'Creative Kids Wiki';
$conf['start'] = 'README.md';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['datadir'] = './data/pages';
$conf['mediadir'] = './data/pages';

// end auto-generated content
